name: Tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run prettier
      - run: npm run lint
      - run: npm test
